###服务端口号
server:
  port: 8500
  
spring:
  application:
    name: tx-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?useSSL=false
    username: root
    password: password

